### ISSUE TITLE
when i tried to start showing NgModule issue

### ISSUE THREAD

**Issue by saikatkoley** [bradtraversy/iweather#5]
[20:23:24]  ionic-app-script task: "serve"
[app-scripts] [20:23:24]  Error: C:\ionicproject\iweather\src\pages\home\home.ts has a @IonicPage decorator, but it does not have a
[app-scripts]             corresponding "NgModule" at C:\ionicproject\iweather\src\pages\home\home.module.ts
[app-scripts] Error: C:\ionicproject\iweather\src\pages\home\home.ts has a @IonicPage decorator, but it does not have a corresponding "NgModule" at C:\ionicproject\iweather\src\pages\home\home.module.ts
[app-scripts]     at new BuildError (C:\ionicproject\iweather\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
[app-scripts]     at C:\ionicproject\iweather\node_modules\@ionic\app-scripts\dist\preprocess.js:18:21

**Comment by saikatkoley** [comment]
Today I have done some fix but now only blank page is showing.

**Comment by LeanSeverino1022** [comment]
I've experienced same issue. Any solution?
